// Typo tools are set of tool and common functions used as constant part
// of code generated by typo. Genearted code should refer to standard 
// libraries and to this header file only. But feel free to extend it
// or add any of includes of your choice to it. In such case it is preferable
// to add also your own copyright before section of your code.

// (c) TYPO by WGan 2021

#ifndef _TYPO_TOOLS_H_
#define _TYPO_TOOLS_H_

#include <string>
#include <type_traits>

namespace TypoTools
{

    template <class TARGET, class SOURCE, bool CAN_COPY> struct Copier
    {
        static void copy(TARGET & target, const SOURCE & source)
        { 
        }
    };

    template <class TARGET, class SOURCE> struct Copier<TARGET, SOURCE, true>
    {
        static void copy(TARGET & target, const SOURCE & source)
        {
            static_cast<SOURCE &>(target) = source;
        }
    };

    template <class TARGET, class SOURCE> void copyIfPossible(TARGET & target, const SOURCE & source)
    {
        Copier<TARGET, SOURCE, std::is_base_of<TARGET, SOURCE>::value>::copy(target, source);
    }

}

#endif