// Typo tools are set of tool and common functions used as constant part
// of code generated by typo. Genearted code should refer to standard 
// libraries and to this header file only. But feel free to extend it
// or add any of includes of your choice to it. In such case it is preferable
// to add also your own copyright before section of your code.

// (c) TYPO by WGan 2021

#include "typo_tools.h"

